targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: git_touch|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            URI:
              name: String
            GitObjectID:
              name: String
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: git_touch|lib/graphql/schema.graphql
          custom_serializers:
            - import: package:git_touch/utils/date_time_serializer.dart
              name: DateTimeSerializer
