targets:
  $default:
    builders:
      json_serializable:
        options:
  github:
    sources:
      - lib/gql_github/*
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: git_touch|lib/gql_github/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            URI:
              name: String
            GitObjectID:
              name: String
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: git_touch|lib/gql_github/schema.graphql
          custom_serializers:
            - import: package:git_touch/utils/date_time_serializer.dart
              name: DateTimeSerializer
  gitlab:
    sources:
      - lib/gql_gitlab/*
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: git_touch|lib/gql_gitlab/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: git_touch|lib/gql_gitlab/schema.graphql
