name: git_touch
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.13.0+26

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  ferry:
  ferry_flutter:
  file_icon:
  filesize:
  fimber:
  fluro:
  flutter_highlight:
  flutter_markdown:
  flutter_svg:
  flutter_vector_icons:
  github:
  github_trending:
  gql_http_link:
  http:
  # in_app_review:
  intl:
  json_annotation:
  launch_review:
  nanoid:
  package_info:
  primer:
  provider:
  share:
  shared_preferences:
  timeago:
  tuple:
  uni_links:
  universal_io:
  uri:
  url_launcher:
  webview_flutter:
  sentry_flutter:
  pub_semver:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  ferry_generator:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - google_fonts/
flutter_intl:
  enabled: true
